agency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')),
    path('', include('pages.urls')),
    path('trips/', include('trips.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
]

trips/urls.py
from django.urls import path

from trips import views


urlpatterns = [
    path("", views.get_trip_list, name="trip_list"),
    path("<int:pk>/", views.get_trip_details, name="trip_details"),
]

pages/models.py
from django.db import models

# Create your models here.

trips/models.py
from django.db import models
from django.utils.text import Truncator
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit


class Continent(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = "continent"
        verbose_name_plural = "continents"

    def __str__(self) -> str:
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=50)
    continent = models.ForeignKey(Continent, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "country"
        verbose_name_plural = "countries"

    def __str__(self) -> str:
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50)
    country = models.ForeignKey(Country, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "city"
        verbose_name_plural = "cities"

    def __str__(self) -> str:
        return self.name


class Hotel(models.Model):
    name = models.CharField(max_length=40, null=False)
    standard = models.IntegerField()
    description = models.TextField("description", null=False)
    city = models.ForeignKey(City, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "hotel"
        verbose_name_plural = "hotels"

    def __str__(self) -> str:
        return self.name

    @property
    def short_description(self):
        truncator = Truncator(self.description)
        return truncator.words(10)


class Airport(models.Model):
    name = models.CharField(max_length=255)
    city = models.ForeignKey(City, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = "airport"
        verbose_name_plural = "airports"

    def __str__(self) -> str:
        return self.name


class Trip(models.Model):
    BED_AND_BREAKFAST = "BB"
    HALF_BOARD = "HB"
    FULL_BOARD = "FB"
    ALL_INCLUSIVE = "AI"
    TYPES = [
        (BED_AND_BREAKFAST, "Bed & Breakfast"),
        (HALF_BOARD, "Half Board"),
        (FULL_BOARD, "Full Board"),
        (ALL_INCLUSIVE, "All Inclusive"),
    ]

    from_city = models.ForeignKey(
        City, null=True, on_delete=models.CASCADE, related_name="from_trips"
    )
    from_airport = models.ForeignKey(
        Airport, null=True, on_delete=models.SET_NULL, related_name="from_trips"
    )
    to_city = models.ForeignKey(
        City, null=True, on_delete=models.CASCADE, related_name="to_trips"
    )
    to_hotel = models.ForeignKey(
        Hotel, null=True, on_delete=models.SET_NULL, related_name="to_trips"
    )
    to_airport = models.ForeignKey(
        Airport, null=True, on_delete=models.SET_NULL, related_name="to_trips"
    )
    date_of_departure = models.DateTimeField()
    date_of_return = models.DateTimeField()
    number_of_days = models.IntegerField()
    trip_type = models.CharField(max_length=2, choices=TYPES)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    price_for_adult = models.FloatField(null=True, blank=True)
    price_for_child = models.FloatField(null=True, blank=True)
    promoted = models.BooleanField(default=False)
    number_of_adults = models.IntegerField(default=0)
    number_of_children = models.IntegerField(default=0)


class Photo(models.Model):
    photo = models.ImageField(upload_to="trips/")
    photo_xs = ImageSpecField(
        source="photo",
        processors=[ResizeToFit(180, 120)],
        format="JPEG",
        options={"quality": 60},
    )
    photo_sm = ImageSpecField(
        source="photo",
        processors=[ResizeToFit(320, 240)],
        format="JPEG",
        options={"quality": 60},
    )
    photo_md = ImageSpecField(
        source="photo",
        processors=[ResizeToFit(480, 360)],
        format="JPEG",
        options={"quality": 60},
    )
    photo_md = ImageSpecField(
        source="photo",
        processors=[ResizeToFit(640, 480)],
        format="JPEG",
        options={"quality": 60},
    )
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name="photos")
    caption = models.CharField(max_length=255, null=True, blank=True)
    is_cover = models.BooleanField(default=False)

    class Meta:
        verbose_name = "photo"
        verbose_name_plural = "photos"

    def __str__(self) -> str:
        return self.caption if self.caption is not None else self.photo.name


class Purchase(models.Model):
    purchase = models.ForeignKey(Trip, on_delete=models.CASCADE)
    number_of_adults = models.IntegerField()
    number_of_children = models.IntegerField()

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

users/forms.py
from django.contrib.auth.forms import UserCreationForm as AuthUserForm
from django.contrib.auth.forms import UsernameField

from .models import User


class UserCreationForm(AuthUserForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {"username": UsernameField}

pages/views.py
from django.shortcuts import render

from trips.models import Trip


def home(request):
    promoted_trips = (Trip
        .objects
        .prefetch_related('photos')
        .filter(promoted=True)
        .order_by('date_of_departure')[:3]
    )
    return render(request, "pages/home.html", {
        "promoted_trips": promoted_trips
    })

def tickets(request):
   
    return render(request, "pages/tickets.html",)


def about(request):
   
    return render(request, "pages/about.html",)


def contact(request):
   
    return render(request, "pages/contact.html",)

trips/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Trip


def get_trip_list(request):
    trips = Trip.objects.all()
    return render(request, 'trips/trip_list.html', context={
        'trips': trips
    })


def get_trip_details(request: HttpRequest, pk: int) -> HttpResponse:
    trip = (Trip
        .objects
        .select_related(
            "from_city", "from_airport",
            "to_city", "to_airport", "to_hotel"
        )
        .get(pk=pk)
    )
    # trip = get_object_or_404(Trip, pk=pk)
    return render(request, "trips/trip_details.html", context={
        "trip": trip
    })

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import UserCreationForm


def register(request):
    if request.method=="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            return redirect('base.html')
    else:
            form = UserCreationForm()
    return render(request,'users/register.html',{'form':form})

pages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="My Travel Agency Site">
    <meta name="author" content="travel_agency">
    <title>{% block title %}My Travel{% endblock title %}</title>
    <br>
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
    main > .container { padding: 60px 15px 0; }
    </style>
    {% endblock styles %}
    {% block extrastyles %}{% endblock extrastyles %}
</head>
<body class="d-flex flex-column h-100">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">My Travel</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'about' %}">About Us</a>
              </ul>
              <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-secondary" type="submit">Add</button>
              </form>
            </div>
          </div>
        </nav>
      </header>
      
      <main class="flex-shrink-0">
        <div class="container">
          {% if messages %}
          
          {% for message in messages  %}
            <div class="alert alert-{{messages.tags}}">
              {{message}}

            </div>
            
          {% endfor %}
            
          {% endif %}
          {% block content %}{% endblock content %}
        </div>
      </main>
      
    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted">Copyright &copy; 2022 - My Travel </span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

pages/templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
<h4>About</h4>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam omnis consequuntur ipsam saepe asperiores tempore amet? Fugiat adipisci similique, iure debitis commodi rerum nostrum voluptatem totam cumque doloremque itaque veritatis.</p>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde ut qui itaque ipsum quam iste voluptatibus, amet perferendis, quisquam accusamus similique cum quis dolorem. Saepe beatae molestiae eaque perferendis vitae?</p>
{% endblock content %}

pages/templates/pages/contact.html
{% extends 'base.html' %}

{% block content %}
<h4>Contact Us</h4>
<p> Adresa: Tirane</p>

{% endblock content %}

pages/templates/pages/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Promoted Trips</h1>
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        {% for trip in promoted_trips %}
            <div class="carousel-item{% if forloop.first %} active{% endif %}">
                {% for photo in trip.photos.all %}
                    {% if photo.is_cover %}
                        <img src="{{ photo.photo.url }}" class="d-block w-100" alt="{{ photo.phot.caption }}">

                        <div class="carousel-caption d-none d-md-block">
                            <p>{{ photo.caption }}</p>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock content %}

pages/templates/pages/tickets.html
{% extends 'base.html' %}

{% block content %}
<h4>Tickets</h4>
<p> Airplane Tickets</p>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="My Travel Agency Site">
    <meta name="author" content="travel_agency">
    <title>{% block title %}My Travel{% endblock title %}</title>
    <br>
    {% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
    main > .container { padding: 60px 15px 0; }
    </style>
    {% endblock styles %}
    {% block extrastyles %}{% endblock extrastyles %}
</head>
<body class="d-flex flex-column h-100">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">My Travel</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'trip_list' %}">Trips</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
              </ul>
              <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a href="" class="nav-link">Welcome {% if user.get_full_name %}{{ user.get_full_name }}{% else %}{{ user.username }}{% endif %}</a>
                  </li>
                  <li>
                    <form action="{% url 'auth_logout' %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-link nav-link">Logout</button>
                    </form>
                  </li>
                {% else %}
                <li class="nav-item">
                  <a href="{% url 'auth_login' %}" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'registration_register' %}" class="nav-link">Register</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </header>
      
      <main class="flex-shrink-0">
        <div class="container">
          {% if messages %}
          
          {% for message in messages  %}
            <div class="alert alert-{{messages.tags}}">
              {{message}}

            </div>
            
          {% endfor %}
            
          {% endif %}
          {% block content %}{% endblock content %}
        </div>
      </main>
      
    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted">Copyright &copy; 2022 - My Travel </span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

trips/templates/trips/trip_details.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ trip.get_trip_type_display }}</h1>
<p>Depart from: {{ trip.from_airport.name }}, {{ trip.from_city.name }}</p>
<p>Destination: {{ trip.to_airport.name }}, {{ trip.to_city.name }}</p>
<p>Accomodation: {{ trip.to_hotel.name }}</p>
<p>Departure Date: {{ trip.date_of_departure }}</p>
<p>Return Date: {{ trip.date_of_return }}</p>
<p>Price for Adults: ${{ trip.price_for_adult }}</p>
<p>Adults: {{ trip.number_of_adults }}</p>
<p>Price for Children: ${{ trip.price_for_child }}</p>
<p>Children: {{ trip.number_of_children }}</p>
<p>Is promoted: {{ trip.promoted }}</p>
<hr />
<div class="d-flex flex-wrap gap-2 justify-content-around mb-4">
  {% for photo in trip.photos.all %}
  <div class="card">
    <img
      src="{{ photo.photo_sm.url }}"
      alt="{{ photo.caption }}"
      width="{{ photo.photo_sm.width }}"
      height="{{ photo.photo_sm.height }}"
      class="card-img-top"
    />
    <div class="card-body">
      <p class="card-text">photo.caption</p>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

trips/templates/trips/trip_list.html
{% extends 'base.html' %}

{% block content %}

<div class="d-flex flex-wrap gap-2">
{% for trip in trips %}
<div class="card" style="max-width: 23.5%;">
    {% for photo in trip.photos.all %}
        {% if photo.is_cover %}
        <img src="{{ photo.photo.url }}" class="card-img-top" alt="{{ photo.caption }}">
        {% endif %}
    {% endfor %}
    <div class="card-body d-flex flex-column justify-content-between">
      <h5 class="card-title">Trip to {{ trip.to_city.name }}</h5>
      <p class="card-text">{{ trip.to_hotel.description|truncatewords:10 }}</p>
      <a href="{% url 'trip_details' pk=trip.pk %}" class="btn btn-primary">Check it out &hellip;</a>
    </div>
  </div>
{% endfor %}
<div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Today</legend>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Sign up</button>
    </div>
  </form>
  <div class="mt-3">
    <small class="text-muted">
      Already Have An Account? <a class="ml-2" href="#">Sign in</a>
    </small>
  </div>
</div>
{% endblock content %}